# -*- coding: utf-8 -*-
"""forward_chaining (hewan)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JYwJz1AEuexIW9diOm2Ij3sVUmnkhXc2
"""

def forward_chaining(facts, rules):
  inferred = set(facts)
  changed = True
  while changed:
    changed = False
    for rule in rules:
      if rule["if"].issubset(inferred) and rule["then"] not in inferred:
        inferred.add(rule["then"])
        changed = True
  return inferred

facts = {"has_feathers", "has_beak", "carnivore"}
rules = [
    {"if": {"has_feathers", "has_beak"}, "then": "is_bird"},
    {"if": {"lays_eggs", "is_bird"}, "then": "is_chicken"},
    {"if": {"cannot_fly", "is_bird"}, "then": "is_penguin"},
    {"if": {"carnivore", "is_bird"}, "then": "is_eagle"}
]

result = forward_chaining(facts, rules)
print("Inferred facts:", result)