# -*- coding: utf-8 -*-
"""sistem_pakar_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5qIWM0V8hTVC_99nM1MjhqXpQFhfFL2
"""

from experta import *

class Diagnosis(KnowledgeEngine):

  @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True))
  def flu(self):
    print("Diagnosis: You may have the Flu.")

  @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True))
  def pneumonia(self):
    print("Diagnosis: You may have Pneumonia.")

  @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False))
  def cold(self):
    print("Diagnosis: You may have a Common Cold.")

  @Rule(Fact(sore_throat=True) & Fact(fever=True))
  def throat_infection(self):
    print("Diagnosis: You may have a Throat Infection.")

  @Rule(NOT(Fact(cough=True)) & NOT(Fact(fever=True)) & NOT(Fact(fatigue=True)) & NOT(Fact(breathing_difficulty=True)) & NOT(Fact(sneezing=True)) & NOT(Fact(runny_nose=True)) & NOT(Fact(sore_throat=True)))
  def healthy(self):
    print("Diagnosis: You seem healthy.")

#Tugas Menambahkan Minimal 4 penyakit Baru

  @Rule(Fact(breathing_difficulty=True) & Fact(wheezing=True) & Fact(coughing_at_night=True))
  def asthma(self):
    print("Diagnosis: Kamu mungkin mengalami Asma.")

  @Rule(Fact(fever=True) & Fact(joint_pain=True) & Fact(skin_rash=True))
  def dengue_fever(self):
   print("Diagnosis: Kamu mungkin mengalami Demam Berdarah.")

  @Rule(Fact(chest_pain=True) & Fact(fatigue=True) & Fact(dizziness=True))
  def hypertension(self):
    print("Diagnosis: Kamu mungkin mengalami Darah Tinggi.")

  @Rule(Fact(fatigue=True) & Fact(dizziness=True) & Fact(blurred_vision=True))
  def hypotension(self):
    print("Diagnosis: Kamu mungkin mengalami Darah Rendah.")



def get_input():
  """Helper function to get user input and convert to boolean (yes/no)."""
  def ask_question(question):
    while True:
      answer = input(question + " (yes/no): ").strip().lower()
      if answer in ["yes", "no"]:
        return answer == "yes"
      else:
        print("Invalid input. Please answer with 'yes' or 'no'.")

  return {
      "cough": ask_question("Do you have a cough?"),
      "fever": ask_question("Do you have a fever?"),
      "fatigue": ask_question("Do you feel tired or fatigued?"),
      "breathing_difficulty": ask_question("Do you have difficulty breathing?"),
      "sneezing": ask_question("Are you sneezing?"),
      "runny_nose": ask_question("Do you have a runny nose?"),
      "sore_throat": ask_question("Do you have a sore throat?"),
#MENAMBAHKAN 7 PERTANYAAN BARU
      "wheezing": ask_question("Apakah kamu mengalami bunyi mengi saat bernapas?"),
      "coughing_at_night": ask_question("Apakah kamu sering batuk di malam hari atau saat beraktivitas fisik?"),
      "joint_pain": ask_question("Apakah kamu merasakan nyeri pada sendi?"),
      "dizziness": ask_question("Apakah kamu merasa pusing atau berkunang-kunang?"),
      "blurred_vision": ask_question("Apakah kamu mengalami penglihatan kabur?"),
      "skin_rash": ask_question("Apakah kamu memiliki ruam pada kulit?"),
      "chest_pain": ask_question("Apakah kamu merasakan nyeri dada?")
  }


# running the expert system
if __name__ == "__main__":
  symptoms = get_input()
  engine = Diagnosis()
  engine.reset() # reset the knowledge engine

  for symptom, present in symptoms.items():
      engine.declare(Fact(**{symptom: present}))

  engine.run() # run the inference engine