# -*- coding: utf-8 -*-
"""sistem_pakar_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVsylMLmtJjJXNUqX2luP78_AA8mjul8
"""

from experta import *

class SistemPakarMedis(KnowledgeEngine):

  @Rule(Fact(demam=True) & Fact(batuk=True))
  def flu(self):
    print("Diagnosis: Flu.")

  @Rule(Fact(sakit_tenggorokan=True) & Fact(demam=True))
  def throat_infection(self):
    print("Diagnosis: Radang Tenggorokan.")

  @Rule(Fact(nyeri_otot=True) & Fact(nyeri_perut=True))
  def hernia(self):
    print("Diagnosis: Hernia. Innalilahi")

# Tugas Menambahkan 4 Penyakit Baru
  @Rule(Fact(sesak_napas=True) & Fact(batuk=True) & Fact(wheezing=True))
  def asma(self):
    print("Diagnosis: Asma. Gunakan inhaler jika diperlukan dan hindari pemicu.")

  @Rule(Fact(batuk_berdarah=True) & Fact(demam=True) & Fact(berat_badan_turun=True))
  def tbc(self):
    print("Diagnosis: TBC. Segera periksa ke dokter untuk penanganan lebih lanjut.")

  @Rule(Fact(demam=True) & Fact(sakit_perut=True) & Fact(nyeri_sendi=True))
  def tipes(self):
    print("Diagnosis: Tipes. Istirahat yang cukup dan minum antibiotik sesuai resep dokter.")

  @Rule(Fact(perut_perih=True) & Fact(mual=True) & Fact(lambung_terasa_penuh=True))
  def maag(self):
    print("Diagnosis: Maag. Hindari makanan pedas, asam, dan jangan telat makan.")


#Running the expert system
engine = SistemPakarMedis()
engine.reset()
engine.declare(Fact(batuk=True))
engine.declare(Fact(wheezing=True))
engine.declare(Fact(sesak_napas=True))
engine.run()